### ISSUE TITLE
A compile error will occur

### ISSUE THREAD

**Issue by testfooyy** [malt03/PictureInPicture#3]
<img width="816" alt="2017-11-02 2 23 29" src="https://user-images.githubusercontent.com/28691623/32287708-f59391e0-bf74-11e7-9af4-ae2bf0107821.png">

**Comment by malt03** [comment]
You should recompile the framework.
You cannot import a framework compiled with Swift 4.0 in Swift 4.0.2.

**Comment by malt03** [comment]
@testfooyy
